In [26]:
import numpy as np

# Creation Of Numpy Array

In [27]:
a1 = np.array([10, 20, 30, 40, 50])
print(a1)
print(*a1)

[10 20 30 40 50]
10 20 30 40 50


In [28]:
a1 = np.array((10, 20, 30, 40, 50, 60))
print(a1)
print(*a1)
print(a1.ndim)

[10 20 30 40 50 60]
10 20 30 40 50 60
1


In [29]:
type(a1)

numpy.ndarray

In [30]:
a1 = np.array(34) # 0 dimension array
print(a1)
print(a1.ndim)

34
0


In [31]:
type(a1)

numpy.ndarray

In [32]:
a2 = np.array([1, 2, 3, 4, 5]) # 1D array
print(a2)
print(a2.ndim)

[1 2 3 4 5]
1


In [33]:
c = np.array([[1, 2, 3],
              [4, 5, 6]]) # 2D array
print(c)
print(c.ndim)
type(c)

[[1 2 3]
 [4 5 6]]
2


numpy.ndarray

In [34]:
d = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]]) #3D Array

print(d)
print(d.ndim)
type(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


numpy.ndarray

In [35]:
a2 = np.array([[1, 2],[3, 4],[5, 6]])
a2
a2.ndim

2

In [36]:
a2 = np.array([[[1,2],[3,4],[5,6,7]]]) # Only Homogeneous type of data. Here is only 2-2 elements but here i am trying to pass 3 elements in last.
a2.ndim

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 3) + inhomogeneous part.

In [37]:
In NumPy, square brackets [ ] are used to represent dimensions and nesting of arrays.
Think like this:

[] → 1D
[[]] → 2D
[[[]]] → 3D
[[[[]]]] → 4D
The number of nested square brackets = number of dimensions.

SyntaxError: invalid character '→' (U+2192) (2016098306.py, line 4)

In [38]:
a3 = np.array([[1,2],[3,4],['5','6']]) #It converting all the values in str format.
print(a3)

[['1' '2']
 ['3' '4']
 ['5' '6']]


In [39]:
a3 = np.array([[1, 2],[3., 4.],[5, 6]]) #If u put only one float it will convert  all float.
print(a3)
a3.ndim

[[1. 2.]
 [3. 4.]
 [5. 6.]]


2

In [56]:
a3 = np.array([[1,2],[3.,4],['5','6']])# if u put only single decimal here it also convert all float.
a3

array([['1', '2'],
       ['3.0', '4'],
       ['5', '6']], dtype='<U32')

In [41]:
a4 = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) # 3D array.
a4.ndim
print(a4)

a4.ndim

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


3

# TO Know Data Type

In [42]:
a1.dtype

dtype('int64')

In [43]:
a2.dtype

dtype('int64')

In [44]:
a3.dtype

dtype('float64')

In [45]:
a4.dtype

dtype('int64')

In [46]:
c.dtype

dtype('int64')

In [47]:
d.dtype

dtype('int64')

# Declearation Of Data_Type

In [48]:
a5 = np.array([1, 2, 3],dtype ='i4')
a5

array([1, 2, 3], dtype=int32)

In [49]:
a5 = np.array([1, 2, 3],dtype ='int32')
a5

array([1, 2, 3], dtype=int32)

In [50]:
a5 = np.array([1, 2, 3],dtype ='f4')
a5

array([1., 2., 3.], dtype=float32)

In [51]:
a5 = np.array([1, 2, 3],dtype ='S')
a5

array([b'1', b'2', b'3'], dtype='|S1')

In [52]:
a5 = np.array([1, '2', 3.5])
a5

array(['1', '2', '3.5'], dtype='<U32')

In [58]:
a5 = np.array([1, 2, 3.5, True],dtype = 'S')
print(a5)

[b'1' b'2' b'3.5' b'True']


In [59]:
a5 = np.array([1, 2, 3.5, True])
a5

array([1. , 2. , 3.5, 1. ])

In [53]:
int + float  → float
int + string → string
float + string → string

SyntaxError: invalid character '→' (U+2192) (1597682465.py, line 1)

In [54]:
a5 = np.array([1, 2, 3.5, True])# It is converting True into 1 and all to float
a5.dtype
#print(a5)

dtype('float64')

In [55]:
a = np.array([[[2,4,6],[2,4,5]]])
print(a)
a.ndim

[[[2 4 6]
  [2 4 5]]]


3